name: ML Workflow with pytest and Streamlit

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m venv myvenv
        source myvenv/bin/activate
        pip install -r requirements.txt
        pip install pytest  # Explicitly install pytest

    # Step 4: Run pytest for testing
    - name: Run pytest
      run: |
        source myvenv/bin/activate
        pytest tests/test.py -v


