name: ML Workflow with pytest and Streamlit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python environment
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run pytest for testing
    - name: Run pytest
      run: |
        mkdir -p results
        pytest --junitxml=results/test-results.xml

    # Step 5: Upload test results (optional)
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: results/
